config/routes.rb
Rails.application.routes.draw do
  resources :info, only: [:index]
  resources :termsofservice, only: [:index]
  resources :privacypolicy, only: [:index]
  
  get 'villages/show'
  get 'village/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :comment1s
  resources :themes
  resources :rooms do
  	collection do
  	  put 'join'
  	  get 'judge'
  	  get 'room_out'
  	end
  end
  resources :villages do
  	collection do
  	  put 'create'
  	  get 'modal_trigger_show'
  	  put 'resend_show_village'
  	  put 'notif_result_village'
  	end
  end
  
  get 'selectroom/index'
  get 'welcome/index'
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div >
<h1>ようこそ！WEBアプリ内通者へ</h1>
試験公開中 <br>

<%= link_to 'ゲームを始める（部屋選択画面へ）', selectroom_index_path  , class: 'btn btn-primary'  %><br>
<!--<%= link_to 'システムメッセージ通知画面へ', controller: 'home' %><br>-->
<!--<%= link_to 'お題設定画面へ', themes_path %><br>-->
<!--<%= link_to 'コメント１設定画面へ', comment1s_path %><br>-->
</div>

<br>

道具がなくても、スマホひとつでゲームができるように作りました。<br>
現在のお題登録数 : <%= Theme.count  %>個<br>
最初に起動する場合は、30秒ほどかかる事があります。<br>
<%= link_to 'このサイトについて', info_index_path ,class: 'glyphicon glyphicon-exclamation-sign' %><br>

<div style="text-align:right;">
    <span class="frame" >
        <img src="/jack30.jpg">
    </span>
</div>
<br>

<div style="text-align:right;">
当サイトパス　QRコード<br>
    <img src="<%= asset_path "/qrnaiituusya.png" %>" />
</div>

 