config/routes.rb
Rails.application.routes.draw do
  resources :info, only: [:index]
  resources :termsofservice, only: [:index]
  resources :privacypolicy, only: [:index]
  
  get 'villages/show'
  get 'village/show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :comment1s
  resources :themes
  resources :rooms do
  	collection do
  	  put 'join'
  	  get 'judge'
  	  get 'room_out'
  	end
  end
  resources :villages do
  	collection do
  	  put 'create'
  	  get 'modal_trigger_show'
  	  put 'resend_show_village'
  	  put 'notif_result_village'
  	end
  end
  
  get 'selectroom/index'
  get 'welcome/index'
  get 'home/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

  def self.createRoomNum
    # roomNumのユニーク値算出
    max = Room.maximum(:roomNum)
    if max.nil?
    	roomNumOrd = 1
    else
    	roomNumOrd = max + 1
    end
    
    return roomNumOrd
  end


  # 表示向けデータ作成(一覧)
  def self.getRoomIndexText
    # return @roomNum[],@ownName[],@memberTxt[]
    
    @rooms = self.all
      
  	@roomNum = []
  	@ownName = []
  	@memberTxt = []

  	@rooms.each do |room|
  		if room.position == "owner"
  		  @roomNum.push(room.roomNum)
  		  @ownName.push(room.name)
  		  @memberTxt.push(nil)
  		end
  	end

  	@rooms.each do |room|
      if room.position == "member"
      
        # エラーケースへの自浄行動
        if @roomNum.index(room.roomNum).nil?
          logger.debug("★★エラー！！！memberは存在するが、ownerが存在しない　自浄作業が必要な状況")
          Room.where(id: room.id).delete_all
        else
          index = @roomNum.index(room.roomNum)
          # logger.debug("room.id=#{room.id}")
          # logger.debug("index=#{index}")
          # logger.debug("@memberTxt=#{@memberTxt}")
          
          if @memberTxt[index] == nil
            @memberTxt[index] = room.name
          else
            @memberTxt[index] = @memberTxt[index] + "," + room.name
          end  		    
          
        end
      end
  	end
    	
    #　配列順序　逆順へ
    @roomNum.reverse!
    @ownName.reverse!
    @memberTxt.reverse!

  	return @roomNum,@ownName,@memberTxt
      
  end
    
  # 表示向けデータ作成(部屋個別)
  def self.getRoomShowText(roomNum)
    # return @showRoomNum,@showOwnName,@showMemberTxt[]

    @rooms = self.where(roomNum: roomNum)
      
  	@showRoomNum = ""
  	@showOwnName = ""
  	@showMemberTxt = []

  	@rooms.each do |room|
  		if room.position == "owner"
  		  @showRoomNum = room.roomNum
  		  @showOwnName = room.name
  		else # memberの場合
  		  @showMemberTxt.push(room.name)
  		end
  	end

    return @showRoomNum,@showOwnName,@showMemberTxt
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
    def create
      logger.debug("createに入りました")
      logger.debug(params)

    	@room = Room.new(name:params[:name],position:"owner",roomNum: Room.createRoomNum)
    	@room.save
    	redirect_to @room
    end
    
    def index
      # roomDBの異常値チェック
      # roomNum:Nilがあった場合は削除
      Room.where(roomNum: nil).delete_all

      @roomNum = []
      @ownName = []
      @memberTxt = []
      
      @roomNum,@ownName,@memberTxt = Room.getRoomIndexText

    end
    
    
    def join
      logger.debug("joinに入りました")
      logger.debug(params)
      
      # 参加した部屋がない場合
      if Room.where(roomNum: params[:roomNum]).blank?
        redirect_to action: 'index'
        return
      end
      
      
      # 存在しない場合は、追加する
      if Room.where(name: params[:name]).where(roomNum: params[:roomNum]).blank?
        @room = Room.new(name: params[:name],position:"member",roomNum: params[:roomNum])
        
      	@room.save
      else # すでに存在する場合は追加しない
        @roomTmp = Room.where(name: params[:name]).where(roomNum: params[:roomNum])
        @room = @roomTmp[0]
      end
      
      if @room.position == "member"
        ChatChannel.broadcast_to('message', {"message"=>"room_controlle_join", "roomNum"=>params[:roomNum], "name"=>params[:name],  "action"=>"join_room"})
      end
      
    	redirect_to @room
    end
    
    def room_out
      logger.debug("rooms#room_outに入りました")
      logger.debug(params)
      
      if Room.where(id: params[:roomId]).empty?
        # nilの時は、なにも処理しない
      else
        @room = Room.find(params[:roomId])
        @brcst_roomNum = @room.roomNum.to_s # バッチ処理のため、外部変数が必要
        @brcst_name = @room.name            # バッチ処理のため、外部変数が必要
        
        if @room.position == 'owner'
          ChatChannel.broadcast_to('message', {"message"=>"room_controlle_close", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name,  "action"=>"logout_room"})
        else
          ChatChannel.broadcast_to('message', {"message"=>"room_controlle_logout", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name,  "action"=>"logout_room"})
        end
        
        Room.where(id: params[:roomId]).delete_all
      end
      
      redirect_to action: 'index'
    end
    
    
    
    def judge
      logger.debug("judgeに入りました")
      logger.debug(params)
    end
    

    
    def show
      logger.debug("rooms#showに入りました")
      logger.debug(params)
      
      @room = Room.find(params[:id])

      @showRoomNum,@showOwnName,@showMemberTxtAry = Room.getRoomShowText(@room.roomNum)
      
      logger.debug("@showMemberTxt:")
      logger.debug(@showMemberTxt)
      

    end
    

    
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h1>部屋一覧画面</h1>

<table class='table table-striped table-hover'>
  <tr>
    <th>部屋ID</th>
    <th>オーナー</th>
    <th>メンバー</th>
  </tr>
  
  <% for i in 0..((@roomNum.count) -1) do %>
    <tr>
      <td><%= link_to @roomNum[i] ,   join_rooms_path(roomNum: @roomNum[i] , name:current_user.name) ,method: :put , class: 'widelink' %></td>
      <td><%= link_to @ownName[i] ,   join_rooms_path(roomNum: @roomNum[i] , name:current_user.name) ,method: :put , class: 'widelink' %></td>

      <% if @memberTxt[i].nil? %>
        <td><%= link_to '　' , join_rooms_path(roomNum: @roomNum[i] , name:current_user.name) ,method: :put , class: 'widelink' %></td>
      <% else %>
        <td><%= link_to @memberTxt[i] , join_rooms_path(roomNum: @roomNum[i] , name:current_user.name) ,method: :put , class: 'widelink' %></td>
      <% end %>
      
    </tr>
  <% end %>
</table>
<%= link_to '部屋を新規作成' , rooms_path(name: current_user.name ,position:'owner') , method: :post  , class: 'btn btn-primary' %>
<%= link_to '部屋選択画面へ戻る', selectroom_index_path , class: 'btn btn-primary' %><br><br>

app/views/rooms/show.html.erb
 <span id="showvil_datatag" data-roomNum= <%= @room.roomNum %> data-villageNum=0 data-position= <%= @room.position %>  ></span> 

<p>
  <strong>部屋ID:</strong>
  <span id="show_Room_Num"><%= @showRoomNum  %></span>
</p>
 
<p>
  <strong>オーナー:</strong>
  <span id="show_room_owner"> <%= @showOwnName  %> </spna>
</p>

<p>
  <div id="show_room_mem">
    <strong>メンバー:</strong>
    <% @showMemberTxtAry.each do | member | %>
      <span class="label label-default" style="color: white; background-color: #428bca;"><%= member %></span>
    <% end %>
  </div>
</p>


<% if @room.position == 'owner' %>
  <%= link_to '役職を配布する' , villages_path(roomNum: @room.roomNum ,name: @room.name ,roomId: @room.id ) , method: :put  ,:remote => true, class: 'btn btn-primary'  %>
<% else %>
  あなたはメンバーです。オーナーによるゲーム開始をお待ち下さい。<br><br>
<% end %>

<%= link_to '部屋をぬける' , room_out_rooms_path(roomId: @room.id)  ,data: { confirm: '部屋を抜けます。OK?' } , class: 'btn btn-primary' %>


<!-- モーダル・ダイアログ -->
<div class="modal fade" id="modal_start_vil" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">ゲームを開始します</h4>
      </div>
      <div class="modal-body">
        オーナーによって、役職が配布されました。「ゲームを始める」ボタンを押して遷移してください
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_start_vil" class="btn btn-default">ゲームを始める</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal_close_room" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">部屋が閉じられました</h4>
      </div>
      <div class="modal-body">
        オーナーによって、部屋が閉じられました。「部屋一覧に戻る」ボタンを押して移動してください
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_close_room" class="btn btn-default" onclick="location.href='../rooms'">部屋一覧に戻る</button>
      </div>
    </div>
  </div>
</div>

<!-- owner専用　モーダル -->
<% if @room.position == 'owner' %>

  <div class="modal fade" id="modal_err_createVlg_lackmember" tabindex="-1" data-backdrop="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">ゲーム開始　エラー</h4>
        </div>
        <div class="modal-body">
          メンバーが不足している為、ゲームを開始できません。最低でも１名のメンバーが必要です。
        </div>
        <div class="modal-footer">
          <button type="button" id="modal_btn_start_vil" class="btn btn-default" data-dismiss="modal">OK</button>
        </div>
      </div>
    </div>
  </div>

<% end %>



<script>
 $( function() {
  $('#modal_btn_start_vil').click( function () {
    $.ajax({
        url: '/villages/modal_trigger_show',
        type: 'GET',
        data: {roomNum: Number($('#showvil_datatag').data('roomNum')) , villageNum: Number($('#showvil_datatag').data('villageNum')) },
      });
  });
 });
</script>





  
  